name: Build

on:
    push:
        branches: [ main ]
    jobs:
        build:
            name: Build
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v2
                - uses: actions/setup-node@v2
                  with:
                      node-version: 20.x
                - run: npm ci
                working-directory: ./
                - run: npm run build
        working-directory: ./



        