name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: npm ci
        working-directory: ./
      - run: npm run build
        working-directory: ./
      - name: Deploy to Render
        env:
          RENDER_WEBHOOK_URL: https://api.render.com/deploy/srv-cqdbj3ogph6c73a2pve0?key=6Kic1efe_gY
        run: |
          curl -X POST $RENDER_WEBHOOK_URL
